title: atheist.dad
email: ""
description: "Living as an atheist in today's world — thoughts on tech, art, science, opinion, and societal reflection."
baseurl: ""
url: "https://atheist.dad"
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

plugins:
  - jekyll-seo-tag

# Analytics (leave blank and add your ID in README instructions)
google_analytics: ""

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - Gemfile.lock
  - vendor/
