title: atheist.dad
email: ""
description: "A minimal Jekyll blog for atheist.dad"
baseurl: ""
url: "https://atheist.dad"
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

collections:
  posts:
    output: true

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - Gemfile.lock
  - vendor/
  - .jekyll-cache/
